2019-03-04 20:15:41,791 - teradata.udaexec - INFO - Initializing UdaExec...
2019-03-04 20:15:41,794 - teradata.udaexec - INFO - Reading config files: ['/etc/udaexec.ini: Not Found', '/Users/nimaarvin/udaexec.ini: Not Found', '/Users/nimaarvin/Dropbox/DataScience/Python/Py_Working_Dir/Py_Working_Dir/Applied Data Science with Python - Uni Michigan/Introduction to Data Science in Python/udaexec.ini: Not Found']
2019-03-04 20:15:41,795 - teradata.udaexec - INFO - Found run number file: "/Users/nimaarvin/Dropbox/DataScience/Python/Py_Working_Dir/Py_Working_Dir/Applied Data Science with Python - Uni Michigan/Introduction to Data Science in Python/.runNumber"
2019-03-04 20:15:41,795 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2019-03-04 20:15:41,795 - teradata.udaexec - INFO - Removed 0 log files.
2019-03-04 20:15:41,943 - teradata.udaexec - INFO - Checkpoint file not found: /Users/nimaarvin/Dropbox/DataScience/Python/Py_Working_Dir/Py_Working_Dir/Applied Data Science with Python - Uni Michigan/Introduction to Data Science in Python/test.checkpoint
2019-03-04 20:15:41,944 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2019-03-04 20:15:41,944 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: test
 *          Version: 1.0
 *       Run Number: 20190304201541-3
 *             Host: Nimas-MBP
 *         Platform: Darwin-18.2.0-x86_64-i386-64bit
 *          OS User: nimaarvin
 *   Python Version: 3.7.1
 *  Python Compiler: Clang 4.0.1 (tags/RELEASE_401/final)
 *     Python Build: ('default', 'Dec 14 2018 13:28:58')
 *  UdaExec Version: 15.10.0.21
 *     Program Name: /Users/nimaarvin/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py
 *      Working Dir: /Users/nimaarvin/Dropbox/DataScience/Python/Py_Working_Dir/Py_Working_Dir/Applied Data Science with Python - Uni Michigan/Introduction to Data Science in Python
 *          Log Dir: /Users/nimaarvin/Dropbox/DataScience/Python/Py_Working_Dir/Py_Working_Dir/Applied Data Science with Python - Uni Michigan/Introduction to Data Science in Python/logs
 *         Log File: /Users/nimaarvin/Dropbox/DataScience/Python/Py_Working_Dir/Py_Working_Dir/Applied Data Science with Python - Uni Michigan/Introduction to Data Science in Python/logs/test.20190304201541-3.log
 *     Config Files: ['/etc/udaexec.ini: Not Found', '/Users/nimaarvin/udaexec.ini: Not Found', '/Users/nimaarvin/Dropbox/DataScience/Python/Py_Working_Dir/Py_Working_Dir/Applied Data Science with Python - Uni Michigan/Introduction to Data Science in Python/udaexec.ini: Not Found']
 *      Query Bands: ApplicationName=test;Version=1.0;JobID=20190304201541-3;ClientUser=nimaarvin;Production=False;udaAppLogFile=/Users/nimaarvin/Dropbox/DataScience/Python/Py_Working_Dir/Py_Working_Dir/Applied Data Science with Python - Uni Michigan/Introduction to Data Science in Python/logs/test.20190304201541-3.log;UtilityName=PyTd;UtilityVersion=15.10.0.21
********************************************************************************/
2019-03-04 20:15:41,945 - teradata.udaexec - INFO - Creating connection: {'method': 'odbc', 'system': 'HOST', 'username': 'UID', 'password': 'XXXXXX', 'driver': 'DRIVERNAME'}
2019-03-04 20:15:41,945 - teradata.udaexec - ERROR - Unable to create connection: {'method': 'odbc', 'system': 'HOST', 'username': 'UID', 'password': 'XXXXXX', 'driver': 'DRIVERNAME'}
Traceback (most recent call last):
  File "/Users/nimaarvin/anaconda3/lib/python3.7/site-packages/teradata/udaexec.py", line 183, in connect
    **args))
  File "/Users/nimaarvin/anaconda3/lib/python3.7/site-packages/teradata/tdodbc.py", line 427, in __init__
    connectParams["DRIVER"] = determineDriver(dbType, driver)
  File "/Users/nimaarvin/anaconda3/lib/python3.7/site-packages/teradata/tdodbc.py", line 381, in determineDriver
    " Available drivers: {}".format(driver, ",".join(drivers)))
teradata.api.InterfaceError: ('DRIVER_NOT_FOUND', "No driver found with name 'DRIVERNAME'.  Available drivers: ")
